bacnet-stack/bacnet-stack

- .gitignore
- .travis.yml
- CMakeLists.txt
- cmake-format.yaml
- src/bacnet/datalink/bacsec.c
This PR provides basic support for the bacnet stack for linux/windows/mac
Closes https://github.com/bacnet-stack/bacnet-stack/issues/5
TODO:
> WIP: build: add basic cmake support

- src/bacnet/basic/object/ai.c
- src/bacnet/basic/object/av.c
- src/bacnet/basic/object/channel.c
- src/bacnet/basic/object/iv.c
- src/bacnet/basic/object/lo.c
- src/bacnet/basic/object/netport.c
- src/bacnet/basic/object/osv.c
- src/bacnet/basic/object/piv.c
- src/bacnet/basic/object/schedule.c
- src/bacnet/basic/object/trendlog.c
This conflicts with #12, but also solves the same issue. If you prefer to merge #12 first, then I'm happy to update this PR to fix the conflict.
> Make all demo object variables static.

- .appveyor.yml
- .github/workflows/main.yml
- ports/bsd/mstimer-init.c
this PR makes master pipeline green again... it became broken after activation of appveyor without the config file in the repository -> appveyor did not know what to do
fixing the share library build can be tackled in a later PR
> ci: add mac os to github ci

- src/bacnet/basic/npdu/h_npdu.c
- src/bacnet/basic/service/h_apdu.c
- src/bacnet/basic/tsm/tsm.c
- src/bacnet/timesync.c
Just a view comments and pointer checks.
> Comments and length checks.

- src/bacnet/basic/tsm/tsm.h
this seems to fix a linking issue in my code on windows
example: 
```cpp
Send_I_Am(&Handler_Transmit_Buffer[0]);
```
@madebr you made the windows exports, does this make sense for you?
> fix: linking with cpp code

- src/bacnet/basic/service/h_rp.c
- src/bacnet/basic/service/h_rr.c
> Replaced gotos in handler code

- CMakeLists.txt
- src/bacnet/datalink/dlenv.c
This allows the BACDL_ETHERNET option to be compiled.
> Fixing BACDL_ETHERNET compilation

- west.yml
This manifest file follows a verified template but must be merged to master to fully confirm the settings.
> Add top-level west.yml to become a west manifest repo

- CMakeLists.txt
> Fix CMakeLists mstp.c source include

- src/bacnet/basic/service/s_whois.c
Bug#76 Fix Send_WhoIs_Local destination address. Thanks, Duffy!
> Bug#76 Fix Send_WhoIs_Local destination address

- ports/linux/dlmstp.c
* DSR-1471: fixes data race issues on ring buffer
* DSR-1471: added missing semi-colon
> DSR-1471: fixes data race issues on ring buffer for MSTP (#9)

- src/keylist.c
Corrected keylist to handle signed integer wraparound for large number of nodes.
> Corrected keylist to handle signed integer wraparound

- ports/win32/Microsoft Visual Studio 2019/BACnet Solution Settings.props
- ports/win32/Microsoft Visual Studio 2019/BACnet Stack Development.sln
- ports/win32/Microsoft Visual Studio 2019/BACnet_Handler_Library/BACnet_Handler_Library.vcxproj
- ports/win32/Microsoft Visual Studio 2019/BACnet_Handler_Library/BACnet_Handler_Library.vcxproj.filters
- ports/win32/Microsoft Visual Studio 2019/BACnet_Handler_Library/BACnet_Handler_Library.vcxproj.user
- ports/win32/Microsoft Visual Studio 2019/BACnet_Object_Definitions/BACnet_Object_Definitions.vcxproj
- ports/win32/Microsoft Visual Studio 2019/BACnet_Object_Definitions/BACnet_Object_Definitions.vcxproj.filters
- ports/win32/Microsoft Visual Studio 2019/BACnet_Object_Definitions/BACnet_Object_Definitions.vcxproj.user
- ports/win32/Microsoft Visual Studio 2019/BACnet_Stack_Library/BACnet_Stack_Library.vcxproj
- ports/win32/Microsoft Visual Studio 2019/BACnet_Stack_Library/BACnet_Stack_Library.vcxproj.filters
- ports/win32/Microsoft Visual Studio 2019/BACnet_Stack_Library/BACnet_Stack_Library.vcxproj.user
- ports/win32/Microsoft Visual Studio 2019/Server/Server.vcxproj
- ports/win32/Microsoft Visual Studio 2019/Server/Server.vcxproj.filters
- ports/win32/Microsoft Visual Studio 2019/Server/Server.vcxproj.user
Used Yaniv S posted solution for MS VS 2017 which took
the sln (solution) from version 0.9.1 and updated it to
compile as static lib for 1.x.x branch.
> Added example Visual Studio 2019 project.

- src/bacnet/bacstr.c
- src/bacnet/bacstr.h
Codify the 8-bit size limit for bit-string capacity.
Thank you, Chris Ellec!
> bitstring capacity 8-bit size bug

- ports/stm32f4xx/dlmstp.c
Transmitted frame counter was not counting all frames transmit; it was only counting data frames.  Moved the transmitted frame and PDU counter incrementors to `MSTP_Send_Frame()` to keep them in a single location instead of being scattered.
`Statistics.transmit_frame_counter` is now incremented for every transmitted frame
`Statistics.transmit_pdu_counter` is incremented for every transmitted frame that contains data
> Fix transmitted frame and pdu counters in dlmstp

- .github/workflows/gcc.yml
- Makefile
- ports/lwip/Makefile
- ports/lwip/bacport.h
- ports/lwip/bip.c
Update LwIP 2.x with BACnet/IP 1.x abstraction.
Integrate LwIP build with continuous integration.
> update LwIP BACnet/IP abstraction

- src/bacnet/bacenum.h
- src/bacnet/bactext.c
- src/bacnet/bactext.h
Add enumerations and text for Color and Color Temperature objects
Add enumerations and text for Audit Log and Audit Reporter objects
Add enumerations and text for BACnet/SC Network Port object
> Add new enumerations and text

- src/bacnet/bacenum.h
- src/bacnet/bactext.c
Add new enumerations for BACnet Errors
Add new enumerations from BACnet Errata
Add enumeration text for new enumerations.
> Add enums and text for BACnet Errors

- ports/win32/Microsoft Visual Studio 2019/BACnet_Stack_Library/BACnet_Stack_Library.vcxproj
- ports/win32/Microsoft Visual Studio 2019/BACnet_Stack_Library/BACnet_Stack_Library.vcxproj.filters
- zephyr/CMakeLists.txt
Building any in apps/* has error. Reason - absent hostnport.c in CMakeLists.txt
> Fix build apps/

- ports/atmega168/h_rp.c
Fix the RP handler in atmega168 for use with Arduino ATmega328 board and RS485 shield. 
Thank you [Lance Tollenaar](https://sourceforge.net/p/bacnet/discussion/402141/thread/b0f1816e63/?limit=25#a6d3) for the debugging and posting a solution.
> Fix ports/atmega168 RP handler

- apps/router-ipv6/main.c
- apps/router-mstp/main.c
- ports/win32/dlmstp-mm.c
- ports/win32/dlmstp.c
fixes #142 for cross-compile of router-mstp application
> Remove and fix old usage of MAX_HEADER

- ports/bsd/bip-init.c
- ports/linux/bip-init.c
- ports/win32/bip-init.c
- src/bacnet/datalink/bip.h
- test/bacnet/datalink/mock/src/bip-mock.c
> Provide getter for broadcast BIP socket

- ports/bsd/bip6.c
- ports/linux/bip6.c
- ports/win32/bip6.c
> RFC Feature/bacnet ipv6 bind interface for link local comunication

- src/bacnet/basic/object/bv.c
- src/bacnet/basic/object/lo.c
- src/bacnet/basic/object/mso.c
Fixed array index out of range for binary-value, multistate-output, and lighting-output basic objects. Thanks, Roy!
> Fixed array index out of range for BV, MSO, and LO

- src/bacnet/bacdcode.c
- test/bacnet/bacdcode/src/main.c
Thank you for the bug report,  Mikhail.
> fix BACnet Array size encoding

- west.yml
Verified by:
1. cd $workspace && \ rm -rf modules/ && \ west update && \ zephyr/scripts/twister -p unit_testing \ -T bacnet-stack/zephyr/tests/
Visually verified all tests passed.
> Trim west.yml imported repository set

- west.yml
Verified by:
1. cd $workspace && \ rm -rf modules/ && \ west update && \ zephyr/scripts/twister -p unit_testing \ -T bacnet-stack/zephyr/tests/
Visually verified all tests passed.
> Trim west.yml imported repository set (#460)

- CHANGELOG.md
- apps/mstpcap/main.c
Fixed bug#83 of mstpcap.exe Permission Denied in Wireshark
> Change mstpcap to either write to pipe or file, not both.

- ports/win32/Microsoft Visual Studio/bacnet-stack/bacnet-stack.vcxproj
- ports/win32/Microsoft Visual Studio/bacnet-stack/bacnet-stack.vcxproj.filters
This is a quick and easy one. I also renamed the project filter from the old "win" to "win32" to match the desired directory structure.
> Added new linear.c to Microsoft Visual Studio project

- src/bacnet/basic/object/nc.c
- test/CMakeLists.txt
- test/bacnet/basic/object/nc/src/main.c
PR #516 with fixed commit message
> object/nc: Fix incorrect apdu_len calculation

- ports/win32/Microsoft Visual Studio/bacnet-stack/bacnet-stack.vcxproj
Fixed #534 by removing duplicate cobs.c file in MSVC project
> remove duplicate cobs.c file in MSVC project

- src/bacnet/bacapp.c
Fixed issue #565 by decoding the accumulator SCALE property
> Added bacapp decoding for accumulator SCALE property

- apps/Makefile
- apps/router/Makefile
- apps/router/main.c
- apps/router/network_layer.c
- ports/linux/dlmstp_linux.c
- src/bacnet/basic/bbmd/h_bbmd.c
Fixes #584 by changing CFLAGS settings.
> Fixed makefile for building the Linux router application.

- CHANGELOG.md
- CMakeLists.txt
- src/bacnet/version.h
Changed to version 1.3.4 for release on 2024-03-02.
> Feature/release 1.3.4 prep

- apps/writeprop/main.c
- apps/writepropm/main.c
added some help about decoding complex data in WriteProperty example app
> added some help about decoding complex data in WriteProperty example

- .clang-format
- src/bacnet/basic/object/ai.c
- src/bacnet/basic/object/av.c
Fixed basic analog-value object intrinsic reporting for ack notification.
Fixed basic analog-value object write property of present-value to priority 6.
> Fixed basic analog-value object intrinsic reporting and write property

- src/bacnet/basic/object/bi.c
- src/bacnet/basic/object/bv.c
- src/bacnet/basic/object/calendar.c
- src/bacnet/basic/object/color_object.c
- src/bacnet/basic/object/lo.c
- src/bacnet/lighting.c
Fix datatype conversion errors found by splint.
Fix Binary input/value set.
> Fix datatype conversion errors found by splint.

- src/bacnet/basic/object/device.c
- src/bacnet/basic/service/h_rr.c
This patch makes bacserv pass test 9.21.2.3
> Test 9.21.2.3 array index

- .github/workflows/zephyr.yml
- ports/zephyr/bip-init.c
- ports/zephyr/bip6-init.c
- west.yml
- zephyr/samples/hello_bacnet_stack/sample.yaml
- zephyr/samples/profiles/b-ss/sample.yaml
- Update west.yml
- Update samples.yaml to new syntax, board names
- Patches to ports/zephyr (some stubs)
Verified by:
1. ./zephyr/scripts/twister -p unit_testing -T bacnet-stack/zephyr/tests
2. ./zephyr/scripts/twister -T bacnet-stack/zephyr/samples/ --integration
Fix #721
> Zephyr 3.7.0 integration fixes:

- .github/workflows/zephyr.yml
- ports/zephyr/bip-init.c
- ports/zephyr/bip6-init.c
- west.yml
- zephyr/samples/hello_bacnet_stack/sample.yaml
- zephyr/samples/profiles/b-ss/sample.yaml
- Update west.yml
- Update samples.yaml to new syntax, board names
- Patches to ports/zephyr (some stubs)
Verified by:
1. ./zephyr/scripts/twister -p unit_testing -T bacnet-stack/zephyr/tests
2. ./zephyr/scripts/twister -T bacnet-stack/zephyr/samples/ --integration
Fix #721
> Zephyr 3.7.0 integration fixes: (#723)

- src/bacnet/basic/client/bac-rw.c
> Fixed endless query in bac-rw module when error is returned.

- src/bacnet/basic/object/device.c
- src/bacnet/basic/object/device.h
- zephyr/subsys/bacnet_basic/device.c
Similar to another request [#624] but only affecting the basic device object API.
> Added device WriteProperty callback in basic device examples.

- CMakeLists.txt
Don't use return.
a) this is an if else
b) all apps below this would not be build
> fix app router cmake

- ports/bsd/bip6.c
- ports/linux/bip6.c
Copy debug_fprintf_bip6() from linux
> fix bsd/bip6.c:35:16: error: variadic macros are a C99 feature

- Makefile
- src/bacnet/bacapp.c
- src/bacnet/bacdevobjpropref.c
- src/bacnet/basic/object/ai.c
- src/bacnet/basic/object/av.c
- src/bacnet/basic/object/iv.c
- src/bacnet/basic/object/iv.h
- src/bacnet/basic/object/lsp.c
- src/bacnet/basic/object/lsz.c
- src/bacnet/basic/object/netport.c
- src/bacnet/basic/object/sc_netport.c
- src/bacnet/basic/object/schedule.c
- src/bacnet/basic/sys/days.c
- src/bacnet/datalink/bsc/bsc-hub-connector.c
- src/bacnet/datalink/bsc/bsc-node-switch.c
- src/bacnet/datalink/bsc/bsc-node.c
- src/bacnet/datalink/bsc/bsc-socket.c
- src/bacnet/datalink/bsc/bvlc-sc.c
- src/bacnet/datalink/bsc/bvlc-sc.h
- src/bacnet/datalink/mstp.c
- test/bacnet/datalink/bvlc-sc/src/main.c
Enabled style and CERT-C addon for CPPCHECK with some suppressions and fixed the defects found.
> Enabled style and CERT-C addon for CPPCHECK

- src/bacnet/basic/object/av.c
- src/bacnet/basic/object/av.h
- src/bacnet/basic/object/iv.c
- src/bacnet/basic/object/iv.h
This PR adds write present value callbacks to Analog and Integer value basic objects
> Added write present value callbacks for Analong and Integer values

- src/bacnet/basic/object/device.c
- src/bacnet/basic/object/netport.c
also implement Device_Reinitialize_State_Set
> enable writing mstp mac address and link speed via network_port

- ports/bsd/bip-init.c
- src/bacnet/basic/tsm/tsm.c
- test/bacnet/npdu/CMakeLists.txt
helpful for debugging communication issues
> add a debug print when tsm retries

- .gitignore
- apps/gtk-discover/Makefile
- src/bacnet/bacapp.c
- src/bacnet/bactext.c
- src/bacnet/bactext.h
Added missing enumeration text for Program object: BACnetProgramError, BACnetProgramState, and BACnetProgramRequest
> Added missing enum text for Program object

- src/bacnet/basic/object/lo.c
- src/bacnet/basic/object/lo.h
- src/bacnet/basic/sys/lighting_command.c
- src/bacnet/basic/sys/lighting_command.h
Added lighting command refresh from tracking value API.
> Fixed Lighting Output Relinquish values.
