bacnet-stack/bacnet-stack

src/bacnet/bactext.c

The `bacnet_property_names` in bactext.c match the values in the specification, with the exception of `COV-increment`. This changes it to `cov-increment` to match the specification.

Match property name to name used in specification.

---

.travis.yml

This way we hide the real build system and thus, can replace Makefiles
with Ninja and we won't have to change the build command.
--clean-first parameter will invoke clean target before building.

CI: use cmake --build command to build a project

---

apps/readprop/main.c
apps/readpropm/main.c
apps/readrange/main.c
apps/scov/main.c
apps/ucov/main.c
apps/whohas/main.c
apps/writeprop/main.c
apps/writepropm/main.c
src/bacnet/bactext.c
src/bacnet/bactext.h

I'm not proposing this as a patch to be merged straight away. This change is an example of what I'd like to do across a few of the demo apps. If you like the idea, do you want me to duplicate the StrToX functions across the different apps, or to put them in a common file - and if so, then where would you suggest?
The existing method of calling bacrp requires the user to know the
enumeration value for the object-type and property values. This patch
enhances to allow the object-type and property arguments to be specified
as strings, using the strings as defined in the spec. It does not remove
the old behaviour.
Current:
bacrp 1234 3 1 85
New:
bacrp 1234 binary-input 1 present-value

readprop - allow text strings for object-type and property arguments.

---

src/bacnet/basic/object/netport.c

In the Network Port demo object, Mac_Address appears in all three of `MSTP_Port_Properties_Optional`, `BIP_Port_Properties_Optional` and `BIP6_Port_Properties_Optional`. As a result, due to how the optional properties list is checked in relation to the Network Port's port type, the check for Mac_Address always fails and returns UNKNOWN_PROPERTY.
This PR fixes the problem by getting the appropriate optional properties list for the Network Port object instance and checking all three of required, optional and proprietary properties before returning UNKNOWN_PROPERTY.
Alternatively, a check could be added for Mac_Address specifically, but this would be less maintainable should more common optional properties be added to the Network Port object in later BACnet revisions.
Note that this error …

Fix UNKNOWN_PROPERTY on Mac_Address of Network Port demo object.

---

src/bacnet/basic/object/netport.c

For some reason the Network Port demo object has a Max_APDU_Length_Accepted property in it, but this is not a valid property for a Network Port--at least, not in ANSI/ASHRAE 135-2016 (protocol revision 19). I've scanned the addenda for revision 20 as well and could not find it there, either.
This PR removes the Max_APDU_Length_Accepted property from the Network Port demo object.

Remove Max_APDU_Length_Accepted property from Network Port demo object.

---

src/bacnet/datalink/mstp.c

Addendum 135-2016bm-1 reduces the allowed range for Tusage_timeout in an MS/TP master device from 20-100ms to 20-35ms. Since this addendum falls under protocol revision 20, this PR reduces the value for Tusage_timeout from 95ms to 30ms. The new value satisfies both the pre-addendum and post-addendum range.

Reduce Tusage_timeout from 95ms to 30ms as per 136-2016bm.

---

apps/router/mstpmodule.c
ports/at91sam7s/dlmstp.c
ports/atmega168/dlmstp.c
ports/bdk-atxx4-mstp/dlmstp.c
ports/linux/dlmstp.c
ports/stm32f10x/dlmstp.c
ports/win32/dlmstp.c
ports/xplained/dlmstp.c

Same as #33 but now applied to the customized datalink layers for each of the ports as well. Any that were higher than 35, I've just set to 30.

Reduce Tusage_timeout for all ports.

---

src/bacnet/bacenum.h

Brad asked why the enum was different than the BACnet standard on forum:
[BACnet abort/reject reason data size](https://sourceforge.net/p/bacnet/discussion/402140/thread/8394a30901/)

Fix the Abort and Reject enumeration max and comments.

---

src/bacnet/basic/binding/address.c
src/bacnet/basic/binding/address.h

fixes: "ISO C++ forbids converting a string constant to ‘char*’ [-Wwrite-strings]"

refactor: use const char * instead of char * for inputs

---

src/bacnet/basic/object/av.c
src/bacnet/basic/object/bv.c
src/bacnet/basic/object/csv.c

warning: comparison of array 'wp_data->application_data' equal to a null pointer is always false [-Wtautological-pointer-compare]

fix: compiler warnings Wtautological-pointer-compare

---

src/bacnet/bacapp.c
src/bacnet/bacapp.h

currently there is not way of setting this manually (without changing something in the cmake/make).
As I do not see the usefulness if this macro, just removing it...
@skarg do you have any platform that do not support this? if so, I'd change the behavior to be able to hide this code instead of hide by default.

chore: remove BACAPP_SNPRINTF_ENABLED macro

---

apps/server/main.c

Fixes issue #97. I'm not sure if this is the preferred fix, or to remove setting of device name from the default implementation in device.c.

Set name after call to Init_Service_Handlers()

---

src/bacnet/basic/service/h_rp_a.c

[Bug#74](https://sourceforge.net/p/bacnet/bugs/74/) Printing of the Read property acknowledgement when APDU len is > 255 bytes.  Thank you [unnakb](https://sourceforge.net/u/unnakb/profile/)!

Bug#74 Printing of the Read property acknowledgement

---

apps/router/Makefile
apps/router/ipmodule.c
apps/router/main.c
apps/router/msgqueue.c
apps/router/msgqueue.h
apps/router/mstpmodule.c

Found a number of problems with the router when compiling on linux
* Expected malloc()'ed memory to be zeroed resulting in segfault when attempting to traverse uninitialized dnet list.
* IPC_NOWAIT in main loop means the router sits at 100% cpu utilization polling the main message queue.  fixed by using a blocking wait in that loop and polling in the iplayer threads.
* When configured with two BIP interfaces, broadcast loops ensue because the broadcast traffic is not correctly filtered.  I think the safest thing to do here is to use the SO_BINDTODEVICE setsockopt.

Fixes Issue #157 (Router segfaults)

---

src/bacnet/basic/sys/keylist.c

Fix the keylist to handle large number of nodes where the signed integer
would wrap around.

Fix keylist signed integer wraparound

---

ports/bsd/bip-init.c
ports/linux/bip-init.c
ports/win32/bip-init.c
src/bacnet/datalink/bip.h

Adds a function to return the currently active BIP port.
This is useful for applications that have many of their own sockets and want to maintain a single `select()` call to manage all of them (In my case I want to also run an HTTP server and several other things). This does mean that `select` is called in my application code, and then again in `bip_receive()`, but as far as I'm aware it's safe to call it twice on the same socket.
There's a slight headache in dealing with Windows, as it uses the SOCKET type which can _technically_ be 64 bit and therefore not fit into an `int`, however there seems to be an assumption going back at least 12 years that `int == SOCKET`, and as such it's highly unlikely that Windows will ever change that. This is baked into many applications, most notable …

Add bip_get_socket

---

apps/Makefile

add linker options for stripping dead code. Linux uses GNU ld, while macOS uses lld.
Signed-off-by: Patrick Grimm <patrick@lunatiki.de>

Fixed bsd compile error ld: unknown option: --gc-sections

---

src/bacnet/basic/object/trendlog.c

Valgrind reports some issues inside of Device_Init(), related to passing uninitialized `struct tm` variables into `mktime`:
mktime requires the structure passed must be fully initialised: https://en.cppreference.com/w/c/chrono/mktime#Notes
```
==16775== Conditional jump or move depends on uninitialised value(s)
==16775==    at 0x515D26B: __mktime_internal (in /usr/lib64/libc-2.17.so)
==16775==    by 0x42574F: Trend_Log_Init (trendlog.c:180)
==16775==    by 0x419793: Device_Init (device.c:1834)
==16775==    by 0x40397B: Init_Service_Handlers (main.c:1100)
==16775==    by 0x40397B: main (main.c:1222)
==16775== 
==16775== Conditional jump or move depends on uninitialised value(s)
==16775==    at 0x515D26B: __mktime_internal (in /usr/lib64/libc-2.17.so)
==16775==    by 0x426EEB: …
```

Fix valgrind warnings in trendlog functions

---

ports/at91sam7s/dlmstp.c
ports/atmega168/dlmstp.c
ports/bdk-atxx4-mstp/dlmstp.c
ports/pic18f6720/mstp.c
ports/pic18f97j60/mstp.c
ports/stm32f10x/dlmstp.c
ports/stm32f4xx/dlmstp.c
ports/xplained/dlmstp.c
src/bacnet/datalink/mstp.c

There was a precedent in src/bacnet/datalink/mstp.c to check whether timeouts were already defined before defining them.
Example:
```
#ifndef Treply_timeout
#define Treply_timeout 295
#endif
```
This change extends those `#ifndef` checks to the various ports so that timeouts may be overridden by defining them in bacnet-config.h (assuming `BACNET_CONFIG_H` is defined to cause bacnet-config.h to be included)

Avoid redefining MSTP timeouts

---

apps/epics/main.c
apps/readpropm/main.c
src/bacnet/basic/binding/address.c
src/bacnet/basic/service/h_rpm_a.c
src/bacnet/basic/service/h_rpm_a.h
src/bacnet/basic/service/s_cov.h
src/bacnet/cov.c

A collection of odds and ends changed/fixed while developing my application. This includes:
- Making "rpm_data_free" a public method and using it where appropriate
- Includes fixing memory leak in epics demo application
(note Valgrind indicates that there are more...)
- Fix typo in cov.c
- Allow NULL max_apdu parameter to address_get_by_device
- Add missing include to s_cov.h

Various minor fixes/improvements

---

src/bacnet/basic/object/iv.c

Running the sample BACnet demo server, we noticed that the names of
integer-value types were all "ANALOG VALUE <n>" for some number n which
creates multiple objects with the same object-name.
Signed-off-by: Thomas Jespersen <tj@omnio.net>
---
Thanks for a great library btw, with well-working demos to build off of!

basic/object/iv: Name it "INTEGER VALUE", not "ANALOG VALUE"

---

src/bacnet/basic/object/iv.c

There are a few instances of "Analog Value" in the comments. Make them
"Integer Value" instead.

basic/object/iv: Replace "{Analog -> Integer} Value"

---

CMakeLists.txt

It builds fine with 3.5 too. We had a problem on some old debian with this.

Lower minimal cmake version requirement

---

src/bacnet/basic/binding/address.c

This function is used for BIP MAC, but also for DADR. Some real devices use 2-byte DADR.
This can now be expressed e.g. as `--dadr CA:FE` in the bac app CLI arguments.

Allow "address_mac_from_ascii()" to parse hex 1-6 bytes

---

src/bacnet/datalink/dlenv.c
src/bacnet/datalink/dlenv.h

This is needed when initing as a library, without calling "dlenv_init()". 
That's desirable if you don't want to use env variables and don't want to risk hitting exit() in the function (that should probably be removed).

Make "dlenv_network_port_init()" public (was static)

---

src/bacnet/basic/service/s_cov.c
src/bacnet/cov.h

This is experimental.
I wanted to receive just property 85 COV, but the server sends COV also for other properties of the object.
This was an attempt to send a more selective COV subscription. It did not work in my case, I still receive other properties.
Would be interesting to verify the function against some other bacnet server.

Add option to subscribe to single property COV

---

src/bacnet/datalink/bvlc.c
test/bacnet/datalink/bvlc/src/main.c

1 In bvlc_foreign_device_bbmd_host_address_decode() remove checking of close the common tag.
Reason - the bvlc_foreign_device_bbmd_host_address_encode() is not encode common tag for BACnetHostNPort and bvlc_foreign_device_bbmd_host_address_decode() is not check open tag.
Add and check tag for host only.
Test - test/bacnet/datalink/bvlc.

Fix error in datalink/bvlc.c

---

src/bacnet/config.h
src/bacnet/datalink/datalink.h

PR introduces a define `BACDL_CUSTOM` which allows stack users to externally define functions like `datalink_send_pdu` while playing nicely with the rest of the stack. `datalink.h` ends up defining the prototypes for these functions which are to be externally linked.

Custom datalink support

---

src/bacnet/basic/service/h_arf.c

I think the request should go through in the case the size is the same.

bugfix - Avoid segmentation error if file has capacity size

---

Dockerfile

running `docker build -t bacnet .` wasn't working for me, so I debugged it a little bit to fix the errors

Fix docker build errors

---

src/bacnet/basic/service/h_rpm.c

Right now, the stack is returning empty values/lists, which I understand is not in accordance with the spec.

RPM should return UNKNOWN_OBJECT for non-existent objects

---

src/bacnet/basic/bbmd/h_bbmd.c

Every other `_disable_debug` function sets the associated debug flag to `false`. Looks like a simple copy-paste typo.

Fix typo in bvlc_debug_disable

---

src/bacnet/bacapp.c

print out the Time stamp in ISO 8601 format for event-time-stamps
Signed-off-by: Patrick Grimm <patrick@lunatiki.de>

bacapp print Timestamp Value

---

src/bacnet/basic/service/h_apdu.c

This is tested with Yabe on win32 and bin/bacserv on mac os x.

Fix min data len for UNCONFIRMED_SERVICE_REQUEST from 3 to 2

---

src/bacnet/datalink/datalink.h

Hello,
this is a quick fix to resolve linkage conflict when the stack is added to a C++ project.

Fix linkage conflict when use stack with C++ project

---

apps/epics/main.c

We should use memmove instead of memcpy when things can overlap.
I was looking little bit whole repo and this got my eye.

Fix: Use memmove with overlapping data

---

zephyr/tests/bacnet/basic/object/ao/testcase.yaml
zephyr/tests/bacnet/basic/object/bo/CMakeLists.txt
zephyr/tests/bacnet/basic/object/bo/testcase.yaml
zephyr/tests/bacnet/basic/object/device/testcase.yaml
zephyr/tests/bacnet/basic/object/lc/testcase.yaml
zephyr/tests/bacnet/basic/object/mso/testcase.yaml
zephyr/tests/bacnet/basic/object/netport/testcase.yaml
zephyr/tests/bacnet/datalink/mock/testcase.yaml

Skip $bacnet-stack/zephyr/tests/ failing to build & pass under board `unit_testing`.  This is a temporary fix to allow $bacnet-stack/.github/workflows/zephyr.yml CI pipeline to enable `../zephyr/scripts/twister -p unit_testing -T zephyr/tests`.

[OSCBS-42] skip tests failing unit_testing (temp)

---

src/bacnet/basic/object/bacfile.c
src/bacnet/datalink/bsc/bsc-util.c
test/CMakeLists.txt
test/bacnet/datalink/bsc-datalink/src/main.c

Recent changes to the bacfile object require the presence of a file system.
But the BacNET/SC connection can be used on a device without a file system.
In this case, the use of the bacfile object is not possible.
If there is no file system, the certificates will be present as static arrays in the HW.
The user can set certificates by calling the bsc_node_conf_set_certs() function.
This variant is shown in the test_sc_parameters_static_certs() from test tests/datalink/bsc-datalink.

Fix BACnet/SC tests

---

src/bacnet/bacint.c
test/unit/bacnet/bacint/CMakeLists.txt
test/unit/bacnet/bacint/src/main.c
zephyr/tests/unit/bacnet/bacint/CMakeLists.txt
zephyr/tests/unit/bacnet/bacint/prj.conf
zephyr/tests/unit/bacnet/bacint/testcase.yaml

Fix decode_signed32() length for -8388608 and NULL apdu handling.
Add comprehensive unit tests for bacint.c functionality.
Verified by:
1. (Pass) From $bacnet-stack/test: make clean test
2. (Pass) From $workspace (above $bacnet-stack): west build -p always -b unit_testing \ bacnet-stack/zephyr/tests/unit/bacnet/bacint/ && \ ./build/testbinary
3. (Pass) From $workspace (above $bacnet-stack): ./zephyr/scripts/twister -p unit_testing \ -T bacnet-stack/zephyr/tests/unit/bacnet/bacint/
Signed-off-by: Gregory Shue <gregory.shue@legrand.com>

Fix decode_signed32(); Add unit/bacnet/bacint tests

---

test/ztest/include/zephyr/fff.h

Zephyr is deprecating the zmock library in favor of using the FFF faking library for defining and controlling fake implementations of depended-upon APIs called by the code-under-test.

Add <zephyr/fff.h> from zephyr v3.1.0

---

ports/stm32f4xx/dlmstp.c

STM32M4's MS/TP statistics was missing a dropped token scenario. Should the token be dropped due to a failed pass off, `Statistics.lost_token_counter` was not incremented.

MSTP stat lost_token_counter was missing a drop case

---

src/bacnet/bacdcode.c
test/bacnet/bacdcode/src/main.c

In bacnet_array_encode(), when array-index = ALL for test-encoding start-index =0 (correct) but when writing to pdu then start-index=1. -> mso/state-text all { 'state-2' , 'state-3' }
Thank you, Andreas, for reporting the bug!

Fix BACnetARRAY encoder for index=ALL

---

ports/linux/dlmstp.c

Removed the local variable 'hThread' in 'dlmstp_init' which causes segmentation fault during service exit in dlmstp_cleanup function as this local variable shadows the global variable.

Fix segfault on mstp cleanup on linux port

---

apps/router-mstp/main.c

This bug is a null de-reference in router-mstp when the destination port is not present in the routing table list when processing a routed APDU.  
```
AddressSanitizer:DEADLYSIGNAL
=================================================================
==2924366==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000008 (pc 0x559c932f1a7d bp 0x7fffcdf787a0 sp 0x7fffcdf786c0 T0)
==2924366==The signal is caused by a READ memory access.
==2924366==Hint: address points to the zero page.
#0 0x559c932f1a7d in routed_apdu_handler /mnt/net/lab_share/Bacnet/bacnet-stack-fixes/apps/router-mstp/main.c:914:19
#1 0x559c932f1a7d in my_routing_npdu_handler /mnt/net/lab_share/Bacnet/bacnet-stack-fixes/apps/router-mstp/main.c:971:21
#2 0x559c932f1a7d in main …
```

[router-mstp] DOS: routed_apdu_handler() null dereference 

---

apps/router-mstp/main.c

npdu_len can underflow here if npdu_len ever hits 1 during this loop iteration. This causes `npdu_len -= len` to underflow, which causes the loop to continue past the end of the NPDU. I haven't functionally tested this for regressions, but it no longer crashes.  
```
===================================================================3146750==
ERROR: AddressSanitizer: heap-buffer-overflow on address 0x603000000081 at pc 0x562848e878f7 bp 0x7fffeb15a740 sp 0x7fffeb15a738
READ of size 1 at 0x603000000081 thread T0
#0 0x562848e878f6 in decode_unsigned16 /mnt/net/lab_share/Bacnet/bacnet-stack-fixes/src/bacnet/bacint.c:58:42
#1 0x562848e7c18c in network_control_handler /mnt/net/lab_share/Bacnet/bacnet-stack-fixes/apps/router-mstp/main.c:666:23
#2 0x562848e7c18c in my_routing_npdu_handler …
```

[router-mstp] network_control_handler: Prevent npdu_len from wrapping around at npdu_len=1

---

Makefile
apps/Makefile
apps/fuzz-afl/Makefile
apps/fuzz-afl/README.md
apps/fuzz-afl/main.c
apps/fuzz-libfuzzer/Makefile
apps/fuzz-libfuzzer/README.md
apps/fuzz-libfuzzer/main.c
apps/router-mstp/main.c

Hey Steve,
This one contains both fuzzer harnesses I threw together to fuzz this library (through router-mstp). Let me know if you have any Q's - they'll probably be useful to test any changes or new functionality that get added down the line. If there's functionality beyond what router-mstp exposes, I'm happy to help out re-targeting to hit that stuff as well. 
```
$ make fuzz-afl
$ make fuzz-libfuzzer 
```
I was going to git-submodule the corpus I collected, but I pushed it here instead: https://github.com/CrystalPeakSecurity/bacnet-corpus/tree/main/corpus 
Best,
Anthony

AFL + Libfuzzer harnesses 

---

src/bacnet/bacdcode.c

the original solution caused that after encode_bacnet_address the apdu pointer was moved too far because apdu_len took into account the length of the opening_tag

Fix encode_context_bacnet_address

---

src/bacnet/bacapp.c
src/bacnet/bacdcode.c
src/bacnet/bacdcode.h
test/bacnet/wp/src/main.c

Both `bacapp_data_len()` and `bacnet_tag_number_and_value_decode()` don't enforce bounds checks on APDU accesses properly. 
```
===================================================================102467==
ERROR: AddressSanitizer: heap-buffer-overflow on address 0x621000001100 at pc 0x55df626e7635 bp 0x7fff3f5cf290 sp 0x7fff3f5cf288
READ of size 1 at 0x621000001100 thread T0
#0 0x55df626e7634 in bacapp_data_len /mnt/net/lab_share/Bacnet/bacnet-stack-fixes/src/bacnet/bacapp.c:1531:17
#1 0x55df626fc424 in wp_decode_service_request /mnt/net/lab_share/Bacnet/bacnet-stack-fixes/src/bacnet/wp.c:157:16
#2 0x55df62706c81 in handler_write_property /mnt/net/lab_share/Bacnet/bacnet-stack-fixes/src/bacnet/basic/service/h_wp.c:97:15
#3 0x55df626fe954 in apdu_handler …
```

[libbacnet]: bacapp_data_len() + bacnet_tag_number_and_value_decode()

---

CHANGELOG.md
apps/Makefile
bin/readme.txt
ports/bsd/bacport.h
ports/bsd/bip-init.c
ports/linux/bacport.h
ports/linux/bip-init.c
ports/win32/bacport.h
ports/win32/bip-init.c
src/bacnet/basic/bbmd/h_bbmd.c
src/bacnet/basic/object/bo.c
src/bacnet/basic/tsm/tsm.c
src/bacnet/config.h
src/bacnet/create_object.h
src/bacnet/datalink/bip.h
src/bacnet/datalink/dlenv.c
src/bacnet/delete_object.h
src/bacnet/list_element.h

Fixes #346 by binding the broadcast socket to the port specific broadcast address rather than INADDR_ANY or INADDR_BROADCAST.  Added additional compile options for those who might need them.  For Linux/BSD:
```
#ifdef BACNET_IP_BROADCAST_USE_INADDR_ANY
sin.sin_addr.s_addr = htonl(INADDR_ANY);
#elif BACNET_IP_BROADCAST_USE_INADDR_BROADCAST
sin.sin_addr.s_addr = htonl(INADDR_BROADCAST);
#else
sin.sin_addr.s_addr = BIP_Broadcast_Addr.s_addr;
#endif
```
For Windows:
```
#else
sin.sin_addr.s_addr = BIP_Address.s_addr;
#endif
```
Changed the define `USE_CLASSADDR` to `BACNET_IP_BROADCAST_USE_CLASSADDR` to help manage namespaces.
Added `BACNET_IP_BROADCAST_BIND_ADDR` environment variable to override the default broadcast binding address.

fix BACnet/IP on OS to bind broadcast to specific port

---

src/bacnet/basic/bbmd6/vmac.c

When PRINT_ENABLED is 0, I have a warning with gcc (arm-none-eabi-gcc to be accurate): 'device_id' is not used.

vmac.c : Fix a warning that 'device_id' is not used

---

apps/blinkt/device.c
apps/piface/device.c
ports/at91sam7s/device.c
ports/bdk-atxx4-mstp/device.c
ports/pic18f6720/device.c
ports/rx62n/device.c
ports/stm32f10x/device.c
ports/stm32f4xx/device.c
src/bacnet/basic/object/device.c
src/bacnet/basic/object/device.h
src/bacnet/basic/service/h_dcc.c
test/bacnet/basic/object/device/src/main.c

Fix device object ReinitializeDevice service handling when there is password in the device.
Add API for setting ReinitializeDevice device object password.
Add unit testing of device object ReinitializeDevice service.
Resolves #511 using checks of internal password rather than defines.

Ignore ReinitializeDevice and DeviceCommunicationControl service password

---

src/bacnet/basic/service/h_rpm_a.c

Working on my Calendars branch, I discovered that RPM fails when reading empty `Exception_Schedule` of a `Schedule` object.
This "works" in Master insofar as not returning error, but decoding is not implemented for Special_Event, so you likely get Null anyway.
A comment in `rpm_ack_decode_service_request()` says that `bacapp_decode_known_property()` returns 0 for "empty structure", but this is only true if decoding falls through to `bacapp_decode_generic_property()` or in special cases. Most of the decoders there don't follow this pattern. My Special_Event decoder also does not work that way.
This PR explicitly detects empty value so that empty array is *always* decoded as a single Null value, regardless of the "known property" type.
---
There's some weird corner cases with this (already …

Fix decoding empty array of complex type in RPM

---

demo/handler/h_cov.c

Per interpretation request during BACnet committee meeting today, changed SubscribeCOV Cancellations to always reply with Result(+) instead of object or service errors Result(-).

Bugfix/cov cancellation always succeed 0.8

---

src/bacnet/basic/service/h_cov.c

Per interpretation request during BACnet committee meeting today, changed SubscribeCOV Cancellations to always reply with Result(+) instead of object or service errors Result(-).

Change SubscribeCOV Cancellations to always reply with Result+

---

.github/workflows/gcc.yml
Makefile
apps/Makefile
src/bacnet/basic/bbmd/h_bbmd.c
src/bacnet/basic/object/netport.c
src/bacnet/config.h
src/bacnet/datalink/dlenv.c

Fixes #521 using additional ifdef around data that is required for the BBMD client without a BBMD table.
Note: added another build in root Makefile: make bip-client
Note: changed apps/Makefile BBMD option 'client' and added BBMD option 'full'
```
ifeq (${BBMD},client)
BBMD_DEFINE = -DBBMD_ENABLED=0 -DBBMD_CLIENT_ENABLED
endif
ifeq (${BBMD},full)
BBMD_DEFINE = -DBBMD_ENABLED=1 -DBBMD_CLIENT_ENABLED
endif
```

Fix BACnet/IP builds for BBMD clients without BBMD tables.

---

CHANGELOG.md
apps/mstpcap/main.c
ports/linux/dlmstp.c
ports/linux/dlmstp_linux.c
ports/linux/mstpsnap.c
ports/linux/rx_fsm.c
ports/stm32f4xx/Makefile
ports/stm32f4xx/bacnet.ewp
ports/stm32f4xx/dlmstp.c
ports/win32/dlmstp-mm.c
ports/win32/dlmstp.c
ports/win32/rx_fsm.c
src/bacnet/datalink/cobs.c
src/bacnet/datalink/cobs.h
src/bacnet/datalink/mstp.c
src/bacnet/datalink/mstp.h

Added MSTP extended frame transmit in bacnet/datalink/mstp.c and ports/stm32f4xx/dlmstp.c modules.
Changed RS485_Send_Frame to MSTP_Send_Frame in mstp.c to remove dependency on rs485.h file.

Added MSTP extended frame transmit.

---

CMakeLists.txt

fixed #528 by adding MSVC checking around MSVC specific options to allow CMake to build successfully on Windows with code::blocks tool option.

fix CMake for code::blocks build

---

src/bacnet/basic/service/h_rr.c

Chapter of BACnet norm about Read Range service states in [15.8.1.1.4.1.1 Reference Index]:
_If the item with the index specified in this parameter does not exist, then no items match the criteria for being
read and returned_
Which tells us that we have to return **empty list** when asked in this two cases:
- BY_POSITION, RefIndex <= 0
- BY_POSITION, RefIndex > Buffer_Size
First condition currently isn't made, thats why I think it needs to be removed.

Read Range returns wrong error code, when BY_POSITION and RefIndx == 0

---

Makefile
apps/add-list-element/main.c
apps/create-object/main.c
apps/delete-object/main.c
apps/readfile/main.c
apps/readprop/main.c
apps/readpropm/main.c
apps/readrange/main.c
apps/remove-list-element/main.c
apps/scov/main.c
apps/server-client/main.c
apps/writeprop/main.c
apps/writepropm/main.c
src/bacnet/basic/service/h_apdu.c
src/bacnet/config.h
src/bacnet/create_object.c
src/bacnet/list_element.c
src/bacnet/wpm.c

Fixed issue#551 where config.h set BACNET_SVC_SERVER=1 for apps. Now emitting error for client apps, and not including client functions in APDU handler.

Fixed compilation with BACNET_SVC_SERVER=1 for apps.

---

CMakeLists.txt

Fix build on FreeBSD when cmake is used
Btw, I have added bacnet to FreeBSD ports tree
https://www.freshports.org/devel/bacnet-stack/
https://www.freshports.org/sysutils/bacnet-stack-apps/
Thanks

Fix build on FreeBSD

---

CMakeLists.txt
src/bacnet/basic/object/device.c
src/bacnet/basic/object/lsp.c
src/bacnet/basic/object/lsp.h
test/CMakeLists.txt
test/bacnet/basic/object/lsp/CMakeLists.txt
test/bacnet/basic/object/lsp/src/main.c
test/ztest/src/ztest.c
zephyr/tests/bacnet/basic/object/lsp/CMakeLists.txt

Changed the example Life-Safety-Point object to use Create/Delete-Object.
Added Present_Value, Operation_Expected, and Silenced as Writable.
Enhanced the Life-Safety-Point object unit test.

Change Life-Safety-Point object to use Create/Delete-Object

---

src/bacnet/basic/object/ao.h

In commit 100df01cefe1fd6b26f984c75959c4e898221087 several new functions were added to the analog output objects. In the process however, one call to the BACNET_STACK_EXPORT macro was omitted, the one just before the declaration of Analog_Output_Read_Property:
```text
@@ -142,6 +157,33 @@ extern "C" {
bool oos_flag);
BACNET_STACK_EXPORT
+    bool Analog_Output_Overridden(
+        uint32_t instance);
+    BACNET_STACK_EXPORT
+    void Analog_Output_Overridden_Set(
+        uint32_t instance,
+        bool oos_flag);
+
+    BACNET_STACK_EXPORT
+    BACNET_RELIABILITY Analog_Output_Reliability(
+        uint32_t object_instance);
+    BACNET_STACK_EXPORT
+    bool Analog_Output_Reliability_Set(
+        uint32_t object_instance, BACNET_RELIABILITY value);
+
+    BACNET_STACK_EXPORT
+ …
```

ao.h: add BACNET_STACK_EXPORT macro to Analog_Output_Read_Property function

---

CMakeLists.txt

When calling cmake with -DBAC_ROUTING=OFF, basic/object/gateway/gw_device.c is correctly excluded from the build. 
It does contain however the definition for the functions `Routed_Device_GetNext` and `Routed_Device_Is_Valid_Network`, both of which are called in the `routed_apdu_handler` function of basic/npdu/h_routed_npdu.c. 
This is fine during compilation since these functions' prototypes are declared in basic/object/device.h but linking will fail.
Thus, make the compilation of h_routed_npdu.c conditional depending on the value of `BAC_ROUTING`.

CMakeLists.txt: exclude h_routed_npdu.c when BAC_ROUTING=OFF

---

src/bacnet/basic/object/ai.c
src/bacnet/basic/object/ai.h
src/bacnet/basic/object/av.c
src/bacnet/basic/object/av.h

In this PR I added the following functions to `Analog_Input` and `Analog_Value` objects:
- Name_Set
- Units
- Units_Set
- Description
- Description_Set
For this I needed to add `Object_Name` and `Description` properties to the data structures used by both. The name returned by the `Object_Name` functions was hard-coded to just return "Analog Input" or "Analog Value" respectively with the object instance. Now this will only be returned if the object name has not been set manually by a server application.
When a client would execute a read property request for the `Description` property the behaviour was to just return the object name instead. Now it will return the string stored in the `Description` property of the data structure.
All the newly implemented functions are already declared in …

Add missing object functions to analog inputs and values

---

src/bacnet/basic/object/ao.c

`Analog_Output_Present_Value_Write` hard-coded the lower and upper bounds of a new value to 0 and 100. It should instead use the previously define `Min_Pres_Value` and `Max_Pres_Value` which are set to 0 and 100 by default.
There was no verification of the bounds within `Analog_Output_Present_Value_Set`, therefore using this function, an arbitrary value could be set. I changed this to not update the present value at all if it's outside of the defined bounds.
Maybe we could also change `Analog_Output_Present_Value_Set` to set the object's Present_Value to `Min_Pres_Value` and `Max_Pres_Value` respectively considering according to the standard they indicate "lowest/highest number in engineering units that can be reliably used for the Present_Value".

ao.c: set proper bounds for Analog_Output_Present_Value_Set and Analog_Output_Present_Value_Write

---

src/bacnet/basic/object/bi.c

bi.c: add possibility to set custom descriptions and object names
This PR adds the missing functions `Binary_Input_Name_Set`, `Binary_Input_Description` and `Binary_Input_Description_Set`.
It also changes the behaviour of `Binary_Input_Name` to return the custom object name.
For this we add two new arrays `Description` and `Object_Name` which both contain `MAX_BINARY_INPUT` amount of values.
In order for a client to be able to retrieve the custom description, we need to adapt the `Binary_Input_Read_Property` function so that the new `Binary_Input_Description` function is called then `rpdata->object_type` equals `PROP_DESCRIPTION`.

Add missing binary input functions

---

src/bacnet/basic/object/iv.c

Integer_Values instances start at 1 while other object instances start at 0. Change this to have the same start for all objects.
Is don't see any reason why Integer_Values would start at 1. Is there any ?

Change first instance of an integer value from 1 to 0

---

src/bacnet/rpm.h

When building the stack with readable objects, the [`My_Read_Property_Multiple_Ack_Handler`](https://github.com/bacnet-stack/bacnet-stack/blob/770be70688895ee394b7d607f8b9d96beb40911f/src/bacnet/basic/client/bac-rw.c#L301) function defined in [`src/bacnet/basic/client/bac-rw.c`](https://github.com/bacnet-stack/bacnet-stack/blob/master/src/bacnet/basic/client/bac-rw.c) calls [`rpm_ack_object_property_process`](https://github.com/bacnet-stack/bacnet-stack/blob/770be70688895ee394b7d607f8b9d96beb40911f/src/bacnet/rpm.h#L198) which is defined in [`src/bacnet/rpm.h`](https://github.com/bacnet-stack/bacnet-stack/blob/master/src/bacnet/rpm.h) but unreachable without BACNET_STACK_EXPORT.
How to reproduce the bug:
```
$ mkdir build
$ cd build/
$ cmake -DCMAKE_C_FLAGS="-DMAX_ANALOG_INPUTS=100"  ..
$ …
```

fix build with readable objects

---

src/bacnet/basic/object/nc.c

n the SHRAE 135-2020 table 12-25:
"Transitions BACnet Event Transition Bits A set of three flags that indicate those transitions
{TO_OFFNORMAL, TO_FAULT, TO_NORMAL} for
which this recipient is suitable.
See #618 .

Setting logic behind valid transitions check straight

---

src/bacnet/basic/service/h_apdu.c

BTS has a test on apdu length. The current code responds to telegrams with apdu_len > MAX_APDU.
This patch changes this to timeout.

Add check on apdu_len. Timeout if too long.

---

.github/workflows/main.yml
CMakeLists.txt
apps/epics/main.c
apps/readbdt/main.c
apps/readfdt/main.c
apps/router/main.c
apps/router/msgqueue.c
apps/router/msgqueue.h
apps/router/mstpmodule.c
ports/linux/dlmstp.c
ports/linux/dlmstp_linux.c
src/bacnet/basic/npdu/h_routed_npdu.c
src/bacnet/basic/object/device.c
src/bacnet/datalink/dlenv.c
src/bacnet/hostnport.c

We want that CI builds as much code as possible and show warnings for those. For this reason enable more our own build options. We cannot enable all options for every platform so we need to have some conditions in main.yml.
We also need to fix warnings so build get pass after these new things are enabled. Only bigger thing which is now missing is BACDL_BIP6.

Build more code in CI

---

ports/linux/bip6.c
src/bacnet/basic/service/h_get_alarm_sum.c
src/bacnet/basic/sys/platform.h
src/bacnet/basic/ucix/ucix.c
src/bacnet/datalink/mstp.c

I play with compile flags. I found out that PRINT_ENABLE=0 and BACDL_BIP6=ON triggers some compiler warnings. Fix these so we have cleaner build with all configurations.

Fix couple compiler warnings

---

CMakeLists.txt
ports/arduino_uno/datalink.h
src/bacnet/basic/object/netport.c
src/bacnet/basic/object/netport.h
src/bacnet/config.h
src/bacnet/datalink/datalink.c
src/bacnet/datalink/datalink.h
src/bacnet/datalink/dlenv.c

Before we could define all, one or none datalinks. Improve this so that we can actually just select multiple datalinks. Also now we can take out configure option BACDL_NONE. We just define that, if none is selected.
I choose to do most of the magic in config.h file so that people will not be depended from CMake. Note that I have not test zephyr part. I would be very happy if someone can test that as I do not understand that part yet.
Note that currently when selecting BACNET_STACK_BUILD_APPS and BACDL_BIP6 router-ipv6 will fail to build. This has already been there and will be fixed in other PR.
Releted issues:
- https://github.com/bacnet-stack/bacnet-stack/issues/644
- https://github.com/bacnet-stack/bacnet-stack/issues/205

Make it possible to select multiple datalinks

---

CMakeLists.txt
ports/bsd/dlmstp.c

The dlmstp.c is copy from the Linux port.
If there are timing Problems then i have to adapt mach_absolute_time() MONOTONIC. See TODO
Add bip6 in cmake.
build with
```
cmake .. -G"CodeBlocks - Unix Makefiles" -DBACDL_MSTP=ON -DBACDL_BIP=OFF -DBAC_ROUTING=OFF 
```
run with
```
BACNET_IFACE="/dev/cu.usbserial-14320" BACNET_MSTP_MAC=03 BACNET_MSTP_BAUD=38400 ./readprop 2 device 2 77
```

add mstp support for mac os x

---

CMakeLists.txt

readbdt, readfdt and router-ipv6 can not be built if BACDL_BIP=OFF

fix cmake dependencies

---

CMakeLists.txt
ports/bsd/ethernet.c

Depends on pcap (e.g. with Wireshark)
build with
#cmake .. -G"CodeBlocks - Unix Makefiles" -DBACDL_ETHERNET=ON -DBACDL_BIP=OFF -DBAC_ROUTING=OFF run as normal user (not root) like Wireshark

add ether support for mac os x

---

src/bacnet/hostnport.c

Fix this:
src/bacnet$ arm-none-eabi-gcc -Wall -I.. hostnport.c -c 
In file included from hostnport.c:13:
hostnport.c: In function 'bacnet_bdt_entry_from_ascii': hostnport.c:711:33: warning: array subscript has type 'char' [-Wchar-subscripts]
711 |         if (name && isalnum(name[0])) {
|

Fix a warning with arm-none-eabi-gcc on hostnport.c

---

.github/workflows/gcc.yml

Otherwise, there were a lot of warnings

gcc.yml : Add LEGACY flag to make bip-apps with GNU99

---

CMakeLists.txt

add missing port/linux/dlmstp_linux.c
used by mstpmodule.c

fix app router cmake

---

CMakeLists.txt
apps/router-ipv6/Makefile
apps/router-ipv6/main.c

Makefile use Device_Object_Instance_Number from device-client.c (Device_Object_Instance_Number is not in bacnet.a from Makefile)
Cmake use Device_Object_Instance_Number from libbacnet-stac.a:device.c
This fix #778
With this patch we can turn BACDL_BIP6 on.

fix app router-ipv6: duplicate symbol

---

apps/router/ipmodule.c

with optimize Os the program exits with
bit out of range 0 - FD_SETSIZE on fd_set
Disable optimize for size by static set optimize 2
This Fix #793

fix app router

---

ports/bsd/rs485.c
ports/linux/rs485.c

The usleep() function takes microseconds, not milliseconds. So, T_turnaround needs to be calculated in microseconds. If we don't do this, at a baud rate of 9600, we end up waiting 4 microseconds instead of 4 milliseconds, which goes against the rule.

Fix the MSTP turnaround delay implementation.

---

src/bacnet/datalink/dlenv.c

If -DBACDL_MULTIPLE and runtime env BACNET_DATALINK is null '''
* thread #1, queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=1, address=0x0) frame #0: 0x00007ff819a0e782 libsystem_c.dylib`strcasecmp_l + 91 '''
Set default datalink with priority bip,bip6,mstp,ethernet,arcnet

fix EXC_BAD_ACCESS in datalink_set() strcasecmp()

---

src/bacnet/datalink/dlenv.c

Tested with "server"  and BACNET_PROTOCOL_REVISION=16 on Linux
---
```
diff --git a/apps/Makefile b/apps/Makefile
index 8d99fdadb..afde66117 100644
--- a/apps/Makefile
+++ b/apps/Makefile
@@ -189,7 +189,7 @@ BACNET_DEFINES += -DBACAPP_ALL
BACNET_DEFINES += -DINTRINSIC_REPORTING
BACNET_DEFINES += -DBACNET_TIME_MASTER
BACNET_DEFINES += -DBACNET_PROPERTY_LISTS=1
-BACNET_DEFINES += -DBACNET_PROTOCOL_REVISION=24
+BACNET_DEFINES += -DBACNET_PROTOCOL_REVISION=16
INCLUDES = -I$(BACNET_SRC_DIR) -I$(BACNET_PORT_DIR)
```

Add ability to compile with BACNET_PROTOCOL_REVISION<17

---

src/bacnet/basic/service/h_dcc.c

Fixed DeviceCommunicationControl service handler to return Service Request Denied when the DISABLE parameter is given in protocol-revision 20 or higher builds.

Fixed DeviceCommunicationControl deprecated DISABLE handling

---

src/bacnet/basic/service/h_apdu.c

DeviceCommunicationControl initiation disabled, allows only
- DeviceCommunicationControl
- ReinitializeDevice
- ConfirmedAuditNotification
- UnconfirmedAuditNotification
- WhoIs 
- I-Am services

DCC initiation disabled, only proceess and initiate allowed services

---

CMakeLists.txt

Currently building the `gateway` app with `BAC_ROUTING` off causes the linker to fail, since it depends on implementations in `gw_device.c` (`Add_Routed_Device()` for instance) and `gw_device.c` was being optioned out.
Fixed by adding a check for `BAC_ROUTING` option around the `gateway` app.

Fixed CMakeLists routing option

---

Makefile
src/bacnet/bacdcode.c
src/bacnet/bacdcode.h
src/bacnet/bacdest.c
src/bacnet/bacdest.h
src/bacnet/bacdevobjpropref.c
src/bacnet/bacdevobjpropref.h
src/bacnet/timestamp.c
test/bacnet/bacdcode/src/main.c
test/bacnet/bacdest/src/main.c
test/bacnet/timestamp/src/main.c

Added check for zero length buffer size in primitive decoders that returns zero to enable simpler complex value optional element decoding.

Added check for zero length buffer size in primitive decoders

---

src/bacnet/basic/object/av.c

If trying to write with an invalid type, INVALID_DATA_TYPE should be returned instead of VALUE_OUT_OF_RANGE

av.c, write present value: If type is not valid, don't overwrite error code

---

src/bacnet/basic/object/ms-input.c
src/bacnet/basic/object/msv.c

Read request worked but write request gave "unknown property" error.
PROP_RELIABILITY is already (at least) in AI and AV (meaning that it make sense to add it to MSI and MSV rather than removing its reading).

PROP_RELIABILITY added to MSI and MSV as they answer to read request

---

.pre-commit-config.yaml
apps/Makefile
apps/bacmini/Makefile
apps/bacmini/main.c

Hey Steve,
I thought this `bacmini`  would be a neat app example for people starting out like me!
- Implemented read-only AV and BV switching logic using test values
- Retained writable AO and BO functionality
- Ensured BACnet services continue running without disruption
- Added `apps/bacmini/main.c`
- Added `apps/bacmini/Makefile`
- Updated the root Makefile to include bacmini
- Verified functionality by running `./bin/bacmini`
- Read-only AV/BV correctly cycle through test values
- Writable AO/BO remain commandable
- BACnet server remains operational
This is very neat looking to expand on this with ESP32 and Zephyr next with something more life like that made up switching logic values!!!!
Thanks again for your help and tips!!
Ben

bacmini working for read only av bv and writeable points

---

apps/server-discover/main.c
src/bacnet/basic/client/bac-discover.c
src/bacnet/basic/client/bac-discover.h

This allows folks to use something like `bacdiscover --mac "192.168.1.79:47808"` to discover a BACnet server running on a different port on the same host (as long as the server is using `handler_who_is_unicast`), which is at least useful for developing a BACnet server, but probably has other uses.
- added `bacnet_discover_dest_set` to `bac-discover`
- copied `--dadr` and `--mac` support from `readprop` to `server-discover`

specify a target for discovery

---

ports/bsd/bip-init.c
src/bacnet/hostnport.c

If the `ip_address` in the `BACNET_HOST_N_PORT` `src` is a 4-byte IP4 address, then `host_n_port_to_minimal` refuses to copy it, by passing `sizeof(dst->host.ip_address.address)` (which is 16) to `octetstring_copy_value` as the number of bytes to copy.
`min(sizeof(dst->host.ip_address.address), src->host.ip_address.length)` causes the copy to safely succeed, but maybe there's a better solution?

`host_n_port_to_minimal`: support ipv4 address

---

src/bacnet/bacapp.c
src/bacnet/bactext.c
src/bacnet/bactext.h

Added text sprintf for Network Port object BACnetNetworkType, BACnetNetworkNumberQuality, and BACnetProtocolLevel enumerations.

Added enum text sprintf for Network Port object

---

ports/at91sam7s/dlmstp.c
ports/atmega328/dlmstp.c
ports/bdk-atxx4-mstp/dlmstp.c
ports/pic18f6720/mstp.c
ports/pic18f97j60/mstp.c
src/bacnet/datalink/mstp.c

This fixes segmented Complex-ACK frames which were dropped. This enables all proprietary frames and any new frames to be recieved to the higher layers.

Fixed MS/TP state WAIT_FOR_REPLY to allow reception of any frames that are not known to be not reply frames.
